### PR TITLE
Cleaned up the messy routing

### PR DESCRIPTION
**Pull request by berkutta**
Cleaned up the messy routing

### CODE REVIEW

**Comment by markbeee** [comment]
I intentionally avoided any traces below the antenna section of the ESP-module as it is in your design. There is also one jumper wire - if you etch it as a single sided pcb - not connected (which goes from pin 16 of the CH340G IC  to C3/ R5 on your design). As a jumper wire there is no way to connect it and the board wouldn't function.
The USB to serial lines (from micro USB to CH340G) in your design may also be an issue. Maybe not a the transfer speeds used, but for the sake of same length serial trace lines and angles used for the traces.

**Comment by markbeee** [comment]
May I close the pull request or do you have more remarks on the layout?

**Comment by berkutta** [comment]
Can correct the usb diff. signals and add the other line in the schematics 
if you want.

**Comment by markbeee** [comment]
I really appreciate your pull request, but what would then be different to the current layout? I could put the polygon to ground - which would make sense - but otherwise would be hesitant to change the layout, because the pcb already worked for a lot of people flawlessly. I would suggest closing the pull request if it is ok for you.

**Comment by berkutta** [comment]
No problem. Was just a idea to make the crude looking routing a bit nicer.

**Comment by markbeee** [comment]
Mea culpa for the routing ;) But I prefer fast prototyping working pcbs.

**Pull request closed without merging**
